name: remote ssh command
on: [push]
jobs:

  build:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - name: build & redeploy
      uses: garygrossgarten/github-action-ssh@release
      with:
        command: sh deploy_200-lounge.sh
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
        passphrase: 
        privateKey: ${{ secrets.PRIVATE_KEY}}
